### ISSUE TITLE
Cannot click items in main menu

### ISSUE THREAD

**Issue by EmperorMoose** [SCCapstone/Cupboard#101]
On the home activity, the items in the dropdown menus "Food Expiring Soon", and "Last Modified List" cannot be clicked.

**Comment by WillWells** [comment]
For the expiring foods, we could implement an dialog similar to when a user adds a food to a list from My Cupboard, as well as the option to delete the food. For "last modified list", I'm not sure if we can implement any useful functionality to the user other than displaying the list, unless we have a dialog that asks if the user wants to edit the list.

**Comment by jmstrom** [comment]
Changed Last Modified List to Shopping Lists
Added clickable functionality to Expiring Foods - Takes you to the edit food menu
Added clickable functionality to Shopping Lists - Takes you to whatever shopping list you clicked on
![untitled](https://user-images.githubusercontent.com/23459144/39389365-afd01a2c-4a55-11e8-820e-70f61bd07df9.gif)
