### ISSUE TITLE
Crash from Filtering 

### ISSUE THREAD

**Issue by cjwaldron18** [SCCapstone/Cupboard#107]
When trying to sort My Cupboard by 'Pantry' the app crashes. This is most likely the result of me not having classified any item as a Pantry item. It happens with Freezer and Fridge. Perhaps an issue of a base case. 

![03 - sort pantry crash](https://user-images.githubusercontent.com/23388365/39098647-f7e66456-463b-11e8-8600-ffad5f4bea13.gif)

**Comment by WillWells** [comment]
All items are put in the pantry as a base case. I have not been able to crash it in this way myself, so I'm not sure what could be causing this.

**Comment by WillWells** [comment]
Could not reproduce.
