### ISSUE TITLE
[UI] Toolbar Text

### ISSUE THREAD

**Issue by cjwaldron18** [SCCapstone/Cupboard#108]
Toolbar text is not updating upon returning to the home screen through the navigation menu.
It updates for My Cupboard and Shopping Lists.

![04 - toolbar text](https://user-images.githubusercontent.com/23388365/39098717-fe5718ca-463c-11e8-8a2d-140453a77848.gif)

**Comment by WillWells** [comment]
Fixed with 16e0763
