### ISSUE TITLE
Can't Delete Shopping List

### ISSUE THREAD

**Issue by cjwaldron18** [SCCapstone/Cupboard#109]
I'm not sure how to delete a shopping list. Perhaps add an option to delete a shopping list in the settings area with 'Edit Title'.
![05 - delete shopping list](https://user-images.githubusercontent.com/23388365/39098757-5e15f52e-463d-11e8-92c8-6abd97b238c2.gif)

**Comment by WillWells** [comment]
Deleting a shopping list is done by swiping left on the shopping list, but I agree that it is unclear for users, especially since deletion is done with a button in My Cupboard.

**Comment by KMCGamer** [comment]
@cjwaldron18 I do agree with you though, there should be an option to delete the list while you are on the screen where you can edit it. 

![](https://i.imgur.com/c7NJRa2.gif)
