### ISSUE TITLE
Learn Android Development

### ISSUE THREAD

**Issue by KMCGamer** [SCCapstone/Cupboard#55]
# **DO THIS NO LATER THAN THURSDAY 1/25 12AM**
You should have already seen a couple of these videos so you can skip those if you want.

You will probably want to follow along with these and have android studio open at the same time. Watching is very different than actually doing it. Some of these are videos and some are articles.

Do these is this order:
- [How To Make Android Apps Introduction](https://www.youtube.com/watch?v=ef-6NZjBtW0).
- [Android Fundamentals](https://developer.android.com/guide/components/fundamentals.html). Straight from the people at google themselves. Skim through.
- [How To Make Android Apps 2](https://www.youtube.com/watch?v=kmsB_P2xbus).
- [Introduction to Activities](https://developer.android.com/guide/components/activities/intro-activities.html). Understand what activities are and the many different states they could be in.
- [Activity Life Cycle](https://www.javatpoint.com/images/androidimages/Android-Activity-Lifecycle.png). This is just a diagram. From the previous article you should understand this now.
- [Layout Resources](https://developer.android.com/guide/topics/resources/layout-resource.html). More in depth about resources.
- [How to Make Android Apps 5 - Intents](https://www.youtube.com/watch?v=45gq0Q8GFMM).
- [Fragments](https://developer.android.com/guide/components/fragments.html). Skim through and have a decent understanding of what fragments are and why they are different than activities.

By the time you finish doing this you should be able to make activities, put text on them, navigate to a different screen, and create layouts. This is the bare minimum i would say should get you going. I would continue watching Derek Banas's videos about android development throughout the semester in your own time. They are very good.

**Comment by WillWells** [comment]
Done.
