### ISSUE TITLE
FoodItem Refactor

### ISSUE THREAD

**Issue by KMCGamer** [SCCapstone/Cupboard#61]
Currently our fooditem looks like this.

```java
private UUID mId;
private String mFirebaseId;
private String mName;
private float mQuantity;
private String mUnits;
private String mCategory;
private String mExpiration;
```

I propose that we update it too look like this:

```java
private UUID mId; // ID generated by android for offline use
private String mFirebaseId; // ID generated by firebase for online use
private String mName; // Name of item. ex: milk
private double mQuantity; // Amount of item initially added. ex: 1 gallon
private double mPercentLeft // Amount of item left. ex: 50% or 2 quarts
private String mUnits; // cups, grams, gallons, oz, etc...
private String mCategory; // for sorting. ex: fridge, pantry, dairy, meats, snacks.
private Calendar mExpiration; // calendar object representing expiration date.
private Calendar mDateAdded; // when the item was originally added. used for stats.
```

Thoughts on this?

**Comment by WillWells** [comment]
`private double mPercentLeft`

Percentages could be tricky, but we should definitely put it in.

Case 1: User buys a gallon of milk. They get through 3 quarts and buy another gallon. What would 100% be in this case? A gallon? Two gallons? Does the user decide what 100% is or does the app do it? Should we allow the percentage to go above 100%?

Case 2: User usually buys a gallon of milk, but decides a half gallon would be enough until the next time they go to the store. They enter in the half gallon in the app. Does the app decide that a half gallon is the new 100%?

I think we'll need a way for the user to manually change the 100% value, but the app should default the value as the value entered the first time they enter it into the system, and it doesn't dynamically change unless the user does it.

I don't have any issue with the other changes.
