### ISSUE TITLE
App sometimes crashes when I add an item

### ISSUE THREAD

**Issue by parsonsbatsc** [SCCapstone/Cupboard#80]
It does add the item, because it's there when I start the app again.  However, what do these numbers mean?

![strangenumbersbymilk](https://user-images.githubusercontent.com/2502109/37118779-55b76d6a-2223-11e8-82a2-cb96ef494d94.jpg)

**Comment by WillWells** [comment]
The number in the middle is the current quantity of the item. You can click on it to bring up a dialog to change the quantity of the item. We're planning on changing the look of it to make it less confusing.

I'll look into the crashing.

**Comment by josemvidal** [comment]
I added a bunch of items and it did not crash for me. Emulator with API 26.

**Comment by KMCGamer** [comment]
I noticed that @parsonsbatsc had an account on our app prior to our refactor. This is most likely the cause. I'm going to reset the account in our database to see if this changes anything.

**Comment by KMCGamer** [comment]
Oh wait, I'm sorry I think i was mistaken. I think the account belongs to a different TA.

**Comment by WillWells** [comment]
I also could not recreate the issue. I'm also using an emulator with API 26.

**Comment by parsonsbatsc** [comment]
I was testing on a Galaxy S7.  Possibly different versions of Android?

**Comment by WillWells** [comment]
Could not recreate issue, possible cause was a change in schema from Firebase. Creating a new account would fix the issue if that is the case.
