### ISSUE TITLE
Home screen is confusing

### ISSUE THREAD

**Issue by parsonsbatsc** [SCCapstone/Cupboard#81]
Your shopping list is just separated from what you already have by a blank line.  There's nothing to indicate that the top items are what you have and the bottom ones are a list.

![homepage](https://user-images.githubusercontent.com/2502109/37119257-d0a90d16-2224-11e8-9c3e-eddde6ceda71.jpg)

Also, it would be good if you could collapse the lists.  If you have multiple lists, the home page will get cluttered very quickly.

**Comment by KMCGamer** [comment]
@jmstrom @ZakSlater

**Comment by WillWells** [comment]
The look of Homescreen has been updated as seen in RC1 release.
