### ISSUE TITLE
Notes field does not work

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/Cupboard#97]
![android emulator - nexus_5x_api_26_play 5554 2018-04-17 19-46-48](https://user-images.githubusercontent.com/228704/38904393-2669b25a-4278-11e8-8fda-cfe5e649b64d.png)

**Comment by josemvidal** [comment]
Also, get rid of the "Cancel" and "Add" buttons. You do not need them,

**Comment by WillWells** [comment]
The app does not really make this clear, but currently the description is only used if an item is scanned in with the barcode scanner. We'll make it editable in this screen in case a user wants to add a note.

**Comment by WillWells** [comment]
Functionality added 4859431
